-- MySQL Script generated by MySQL Workbench
-- Wed 21 Apr 2021 10:26:02 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Addresses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NULL,
  `zip_code` INT NULL,
  `Cities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Addresses_Cities1_idx` (`Cities_id` ASC) VISIBLE,
  UNIQUE INDEX `address_UNIQUE` (`address` ASC) VISIBLE,
  CONSTRAINT `fk_Addresses_Cities1`
    FOREIGN KEY (`Cities_id`)
    REFERENCES `mydb`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `addresses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customers_Addresses` (`addresses_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Addresses1`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `mydb`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Restaurants` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Restaurants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `description` NVARCHAR(200) NOT NULL,
  `Addresses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Restaurants_Addresses1_idx` (`Addresses_id` ASC) VISIBLE,
  CONSTRAINT `fk_Restaurants_Addresses1`
    FOREIGN KEY (`Addresses_id`)
    REFERENCES `mydb`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransactionStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TransactionStatus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TransactionStatus` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Menu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Menu_Restaurant1_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_Restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `mydb`.`Restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL,
  `customer_id` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  `TransactionStatus_id` INT NOT NULL,
  `Menu_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Restaurant1_idx` (`restaurant_id` ASC) VISIBLE,
  INDEX `fk_Order_Customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_Orders_TransactionStatus1_idx` (`TransactionStatus_id` ASC) VISIBLE,
  INDEX `fk_Orders_Menu1_idx` (`Menu_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ingredients` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PaymentTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PaymentTypes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PaymentTypes` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Payments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_date` DATE NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `PaymentTypes_id` INT NOT NULL,
  `TransactionStatus_id` INT NOT NULL,
  `Orders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Payment_PaymentTypes1_idx` (`PaymentTypes_id` ASC) VISIBLE,
  INDEX `fk_Payment_TransactionStatus1_idx` (`TransactionStatus_id` ASC) VISIBLE,
  INDEX `fk_Payments_Orders1_idx` (`Orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_PaymentTypes1`
    FOREIGN KEY (`PaymentTypes_id`)
    REFERENCES `mydb`.`PaymentTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_TransactionStatus1`
    FOREIGN KEY (`TransactionStatus_id`)
    REFERENCES `mydb`.`TransactionStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payments_Orders1`
    FOREIGN KEY (`Orders_id`)
    REFERENCES `mydb`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ratings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_recorder` DATE NOT NULL,
  `score` INT(1) NOT NULL,
  `Customers_id` INT NOT NULL,
  `comment` VARCHAR(300) NOT NULL,
  `Restaurants_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Rating_Customers1_idx` (`Customers_id` ASC) VISIBLE,
  INDEX `fk_Ratings_Restaurants1_idx` (`Restaurants_id` ASC) VISIBLE,
  CONSTRAINT `fk_Rating_Customers1`
    FOREIGN KEY (`Customers_id`)
    REFERENCES `mydb`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ratings_Restaurants1`
    FOREIGN KEY (`Restaurants_id`)
    REFERENCES `mydb`.`Restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu_has_Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Menu_has_Ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Menu_has_Ingredients` (
  `Menu_id` INT NOT NULL,
  `Ingredients_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`Menu_id`, `Ingredients_id`),
  INDEX `fk_Menu_has_Ingredients_Ingredients1_idx` (`Ingredients_id` ASC) VISIBLE,
  INDEX `fk_Menu_has_Ingredients_Menu1_idx` (`Menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_has_Ingredients_Menu1`
    FOREIGN KEY (`Menu_id`)
    REFERENCES `mydb`.`Menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menu_has_Ingredients_Ingredients1`
    FOREIGN KEY (`Ingredients_id`)
    REFERENCES `mydb`.`Ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
